MIN_ENTITY_TYPES = [
    "Person",
    "Organization",
    "Location",
    "Product",
    "Concept",
]

FULL_ENTITY_TYPES = [
    "Person",
    "Organization",
    "Location",
    "Date",
    "Time",
    "Money",
    "Percentage",
    "Product",
    "Event",
    "Language",
    "Nationality",
    "Religion",
    "Title",
    "Profession",
    "Animal",
    "Plant",
    "Disease",
    "Medication",
    "Chemical",
    "Material",
    "Color",
    "Shape",
    "Measurement",
    "Weather",
    "Natural disaster",
    "Award",
    "Law",
    "Crime",
    "Technology",
    "Software",
    "Hardware",
    "Vehicle",
    "Food",
    "Drink",
    "Sport",
    "Music genre",
    "Instrument",
    "Artwork",
    "Book",
    "Movie",
    "Tv show",
    "Academic subject",
    "Scientific theory",
    "Political party",
    "Currency",
    "Stock symbol",
    "File type",
    "Programming language",
    "Medical procedure",
    "Celestial body",
]

CUSTOM_ENTITY_TYPES = [
    "ProjectName",
    "Party",
    "Role",
    "Person",
    "ContractDate",
    "Sector",
    "ContractName",
    "ContractType",
    "Location",
    "Country"
]

MARKED_ENTITIES = [
    "Project",
    "Sector",
    "Subsector",
    "ContractName",
    "ContractDate",
    "Country",
    "Location",
    "Party",
    "Role",
    "Person",
    "ContractType"
]

NEW_ENTITIES  = FULL_ENTITY_TYPES + CUSTOM_ENTITY_TYPES